# Generated by Django 5.0.2 on 2024-03-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_offer',
            field=models.BooleanField(default=False),
        ),
    ]
